name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w ./cmd/grove-shell"
    
    - name: Archive
      run: |
          tar -czvf grove-${{ github.event.release.tag_name }}.tar.gz grove LICENSE README.md
  
    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: grove-${{ github.event.release.tag_name }}.tar.gz
        asset_name: grove-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip